cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

notifications:
  email:
    on_success: never
    on_failure: change

language: php

php:
  - 5.6
  - 7.4

services:
  - mysql

addons:
  apt:
    packages:
      - libxml2-utils

env:
  - WP_VERSION=latest WP_MULTISITE=0 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
  - WP_VERSION=trunk WP_MULTISITE=0 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

before_install:
  - nvm install
  - nvm use

install:
  - npm install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f bin/local-dev/travis-ci/apache /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

script:
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"
