cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

notifications:
  email:
    on_success: never
    on_failure: change

language: php

php:
  - 5.6
  - 7.4

services:
  - mysql

addons:
  apt:
    packages:
      - libxml2-utils

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

before_install:
  - nvm install
  - nvm use

install:
  - composer install
  - export PROJECT_SLUG=wp-foo-bar
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"
